language: minimal

jobs:
  include:
    - name: 'Retail'
      script:
        - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

    - name: 'Classic'
      script:
        - export CLASSIC_VERSION="1.13.6"
        - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g $CLASSIC_VERSION

addons:
  apt:
    packages:
      - luarocks

install: luarocks install --local luacheck

before_script:
  - /home/travis/.luarocks/bin/luacheck . --no-color -q -g

notifications:
  email:
    on_success: never
    on_failure: always
